### ISSUE TITLE
Add Link to Freifunk and CCC Website?

### ISSUE THREAD

**Issue by line-o** [refugee-emancipation/crowd-funding#18]
Currently, the logos in the headline do not link anywhere, they are just pictures. Why not make them actual links (as these projects are linked, right?).

**Comment by plutonik-a** [comment]
Yeah, that's a good idea. How do you suppose would be the best way?

**Comment by plutonik-a** [comment]
We will replace the png header for seperate svg-logos and link them to their projects. That will do.
