### ISSUE TITLE
Missing Social Icons on Chrome/Windows

### ISSUE THREAD

**Issue by Oisins** [refugee-emancipation/crowd-funding#83]
Chrome v46.0.2490.71
Windows 7 x64

**Comment by srenatus** [comment]
Hey Oisins, thanks for the notice.

On Windows 7 (64bit) using Chrome version 47.0.2526.16 beta-m, I do see the icons.

Could you check the developer tools' console for error messages, please? Ctrl+Shift+J, also [see here](https://developers.google.com/web/tools/chrome-devtools/debug/console/console-ui?hl=en#opening-the-console).

Thanks!

**Comment by Oisins** [comment]
Only got 1 error:
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT                          http://stats.52k.de/piwik.js

Screen Res: 1366x768

**Comment by srenatus** [comment]
Ok, this is not related. Could you please explain what you're expecting to see vs. what you see?

I've attached a screenshot of the social icons and how they should look like:

![capture](https://cloud.githubusercontent.com/assets/870638/10602397/5bd462c4-7718-11e5-89dd-73eda1d31c1b.PNG)

**Comment by Oisins** [comment]
I meant the Icons on the bottom of the page
Expected:
![expected](https://cloud.githubusercontent.com/assets/11236195/10602734/65b2a42a-771a-11e5-96ac-59fb8ed7ba67.PNG)
Actual:
![actual](https://cloud.githubusercontent.com/assets/11236195/10602729/6032ed0c-771a-11e5-9430-79bef6ce9427.PNG)

**Comment by srenatus** [comment]
Hmm this is weird. So you do see them at the top of the page?

**Comment by Oisins** [comment]
No

![top](https://cloud.githubusercontent.com/assets/11236195/10603168/c6ef3f08-771c-11e5-8962-17e9be1268d6.PNG)

**Comment by srenatus** [comment]
I am out of ideas. You're not using any interfering plugins, by any chance? (You could try opening the page in an icognito-window, which shouldn't load plugins/extensions.)

**Comment by Oisins** [comment]
Adblock Plus was blocking them...

**Comment by srenatus** [comment]
@Oisins How about http://phlow.github.io/feeling-responsive/ .... oh, ok.

**Comment by Oisins** [comment]
Same with that site too

**Comment by srenatus** [comment]
Ok. What do you think, should we close this issue? I suppose fighting adblock plus doesn't make sense.

**Comment by Oisins** [comment]
yeah

**Comment by srenatus** [comment]
Great. Thanks for your help in debugging this. :+1:

**Comment by Oisins** [comment]
np
